### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by tonycoelho** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#47] opened 2018-07-31 21:57 UTC
log4net has default support for environment variables, however it does not work correctly when using this extension. For instance, the file value in the appender below (note - not a full example), includes the environment variable **${LogPath}**. However, this variable is not expanded at runtime and instead logs to the to the literal path ${LogPath}MyApplication.log relative to the executing assembly path. For example, C:\approot\${LogPath}MyApplication.log.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
    <file value="${LogPath}MyApplication.log" />
  </appender>
</log4net>
```

Using environment variables with the log4net section in the an app/web.config  is supported so adding this feature to this extension makes transitioning to .NET Core easier.

**Comment by huorswords** [comment] 2018-08-28 13:04
Hello @tonycoelho ,

Excuse me by the delay on answering you, but I have been very busy on latest weeks.

Regarding your suggestion, I have been trying to reproduce your issue, and, as expected, you are right.

But... creating a .NET Framework 4.6.1 project, and only adding the log4net v.2.0.8 nuget package (without the one of this repo), the issue still is reproduced when you use a sepparate log4net config file.

In order to reproduce, you can create a console application and replace your program.cs content with this code snippet.

``` csharp
namespace sandbox.Test
{
	using log4net;
	using log4net.Config;
	using log4net.Repository.Hierarchy;
	using System;
	using System.IO;
	using System.Reflection;

	class Program
	{
		static void Main(string[] args)
		{
			Assembly assembly = Assembly.GetExecutingAssembly();
			var loggerRepository = LogManager.CreateRepository(assembly, typeof(Hierarchy));
			XmlConfigurator.Configure(new FileInfo("log4net.config"));

			var logger = LogManager.GetLogger(assembly, "TEST");
			
			logger.Fatal("FATAL really fatal");
			Console.ReadLine();
		}
	}
}
```

Also, yo need to add the log4net nuget package, and a log4net.config file, marking it as "Copy Always".

So, as far the issue is related to log4net itself and not this extension, your issue won't be fixed on this repository.

My suggestion for you is to try to resolve the values of your log4net configuration properties using the replacement mechanism that is already available on this extension.

I'm sorry.

Regards,
--
Angel

**Comment by ltan50** [comment] 2018-12-11 13:51
Hi @huorswords, I tried to reproduce the problem as you suggested using framework 4.6.1 but the app did use the environment variable. I used your code snippet exactly and this is my log4net.config file

```xml
<?xml version="1.0" encoding="utf-8" ?>
<log4net>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
    <file value="${LogDir}TestEnvVar\log.txt" />
    <layout type="log4net.Layout.PatternLayout">
      <param name="ConversionPattern" value="%d{ISO8601} [%t] [%-5p] %c - %m [%logger{1}]%n" />
    </layout>
  </appender>
  <root>
    <priority value="ALL" />
    <appender-ref ref="RollingFileAppender" />
  </root>
</log4net>
```
Would you accept a Pull Request?

**Comment by huorswords** [comment] 2018-12-13 07:38
Hi @ltan50 ,

Of course, this repo is always open to receive PR. :)

**Comment by huorswords** [comment] 2019-01-14 15:58
Closed until PR is received.

**Closed by huorswords** 2019-01-14 15:58 UTC
Labels: enhancement, wontfix
