### ISSUE TITLE
latest version does't log to file

### ISSUE THREAD

**Issue by KINGGUOKUN** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#54] opened 2018-12-06 12:17 UTC
when in debug mode and on windows，the log file is created normaly,
but when it is deployed in centos 7, the log file can't be created. The previous version is OK .

**Comment by huorswords** [comment] 2018-12-07 11:20
Hello @KINGGUOKUN ,

Thank you by opening this issue. Could you show / share some code in order to try to reproduce it on my own? I.E. log4net.config file, initialization code...

The last version was modified to use a different way to resolve the path where the application is running. Maybe this is the root cause of your problem, but in order to see what happens, I need some additional information.

Thanks. Regards.

**Comment by huorswords** [comment] 2018-12-07 12:46
Hello again @KINGGUOKUN ,

Thank you by the details. I think that something is missing related to the log4net.config file, but... let's try something.

1. Create a new Console application.
```bash
dotnet new console
```
2. Edit the `Program.cs` file and replace `static void Main(string[] args)` **content** by

```csharp
static void Main(string[] args)
{
    System.Console.WriteLine(AppContext.BaseDirectory);
    System.Console.WriteLine(Environment.CurrentDirectory);
}
``` 
3. Execute it from your centOS 7. The execution result should print on screen two paths.
  * The first path is the one that now the `AddLog4Net()` method is using when the `log4net.config` file is not specified by an absolute path.
  * The second path is the one that is configured on previous versions of the nuget.

Those values should be different. And you need to be sure that the `log4net.config` file is located on the first path.

* Could be something related to the issue #53 already reported?
* Could you try to change the `log4net.config` file copy options from your Visual Studio and deploy it to the centOS 7 machine?

I'll wait to your answer.

Thank you.

**Comment by KINGGUOKUN** [comment] 2018-12-08 11:51
Unfortunately, the two path is same:
/var/projects/PathTest/file.config
/var/projects/PathTest/file.config

And my log configuration file is in the first path.

**Comment by huorswords** [comment] 2018-12-10 07:47
And last question... I hope...

Which is your project's target framework?

**Comment by KINGGUOKUN** [comment] 2018-12-10 11:01
> And last question... I hope...
> 
> Which is your project's target framework? On your original project, not the test one.

.Net core 2.2

**Comment by huorswords** [comment] 2018-12-10 16:36
Hello @KINGGUOKUN ,

Thank you.

I have updated the available [WebApi sample](https://github.com/huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore/tree/feature/54/samples/Sample.WebApi_NetCore22) on branch feature/54 in order to try to "reproduce" your scenario.

I have:
- Set up the appsettings.json to set the log level as `Debug`.
- Created the published application using:
  ```bash
  dotnet publish -c Debug -r ubuntu.18.04-x64
  ```
- Executed the self-contained binaries from my Ubuntu 18.04

- Get data from the values controller using:
  ```bash
  curl http://localhost:5000/api/values
  ```

In my case, the application is showing the messages coming from aspnet core logging (green).

![image](https://user-images.githubusercontent.com/1566221/49746682-fed36080-fca1-11e8-8624-2735a9760895.png)

Can you verify what is the result of executing this sample app on your side?

Maybe it can help to isolate your problem...

Thank you again.

**Comment by KINGGUOKUN** [comment] 2018-12-11 12:03
It says snk not found:
![image](https://user-images.githubusercontent.com/12315104/49799334-a70b2700-fd7f-11e8-9211-aedfe0bc3523.png)
And therefore I can't publish.

**Comment by huorswords** [comment] 2018-12-13 07:47
Sorry @KINGGUOKUN , you are right.

Please, after clone it, on Solution Explorer select the project Microsoft.Extensions.Logging.Log4Net.AspNetCore and go to Project > Properties.

And on the Signing tab, uncheck the Sign assembly checkbox.

![image](https://user-images.githubusercontent.com/1566221/49923385-9e1b7200-feb3-11e8-80c6-59e1326bb0f2.png)

Thank you. Let me know your results.

**Comment by KINGGUOKUN** [comment] 2018-12-17 11:21
Execute the console application:
![image](https://user-images.githubusercontent.com/12315104/50084007-79672780-0230-11e9-9587-eb8d62e04250.png)
![image](https://user-images.githubusercontent.com/12315104/50084074-b03d3d80-0230-11e9-98b6-50a93c261ccf.png)
![image](https://user-images.githubusercontent.com/12315104/50084097-c519d100-0230-11e9-9b46-865f9fa890ff.png)

curl:
![image](https://user-images.githubusercontent.com/12315104/50084160-fbefe700-0230-11e9-9cf1-3109a8e45bef.png)

**Comment by huorswords** [comment] 2018-12-17 16:24
Thank you @KINGGUOKUN.

It seems that using the sample application the log generated is the expected.

Could you review your project configuration to match the configuration on the sample application?

**Comment by KINGGUOKUN** [comment] 2018-12-20 12:04
Well,  I'm really confused.
When I run "dotnet XXX.dll" on windows , the log file is normally created, but fails in CentOS 7.
My project file is in https://github.com/KINGGUOKUN/Account/tree/master/Account.Core/Account

**Comment by huorswords** [comment] 2018-12-31 11:44
I'm confused too. I have tested within an Ubuntu for Windows, rather than CentOS, but works on my side... :\

https://www.dropbox.com/s/1tvs4b759koxfbq/bandicam%202018-12-31%2012-38-22-464.mp4?dl=0

**Comment by huorswords** [comment] 2019-01-08 16:06
@KINGGUOKUN, any news on this?

**Comment by huorswords** [comment] 2019-01-14 15:57
Closing as I cannot reproduce it properly to isolate the problem. Any help will be helpful on this.

**Closed by huorswords** 2019-01-14 15:57 UTC
Labels: bug
