### ISSUE TITLE
%thread in Patternlayout is always empty.

### ISSUE THREAD

**Issue by mike3691** [huorswords/Microsoft.Extensions.Logging.Log4Net.AspNetCore#10] opened 2018-02-22 04:25 UTC
no matter which appender to use, the %thread field always empty.

**Comment by huorswords** [comment] 2018-02-27 10:02
Hello @mike3691,

Thank you very much by using this library.

I was trying to reproduce the issue you mentioned, but I'm not able to do it. I uploaded a branch named "feature/10" with a Test project that writes a Critical message into the console and on a Rolling File, that also has the %thread field on the pattern layout, and I can see the Thread identifier on the log.

Can you checkout the branch and try on your local in order to certify if you could reproduce the problem?

Thank you again. Regards,

**Comment by huorswords** [comment] 2018-03-11 19:30
Hello @mike3691,

As I cannot reproduce the problem, and until you can answer me in order to try to isolate what are you experiencing, I will close this issue.

Thank you. Regards,

**Closed by huorswords** 2018-03-11 19:30 UTC
Labels: bug, cannot reproduce
